# Generated by Django 6.0.1 on 2026-01-22 16:54

import jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_chunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='audio_file',
            field=models.FileField(blank=True, upload_to=jobs.models.Chunk.chunk_audio_upload_path),
        ),
    ]
