# Generated by Django 6.0.1 on 2026-01-25 20:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_chunk_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
