# Generated by Django 6.0.1 on 2026-01-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_chunk_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='max_retries',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='chunk',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
