# Generated by Django 6.0.1 on 2026-02-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_chunk_max_retries_chunk_retry_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='assembled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
