# Generated by Django 6.0.1 on 2026-02-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_assembled_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chunk',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='chunk',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=models.Index(fields=['job', 'status'], name='jobs_chunk_job_id_2d62c8_idx'),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=models.Index(fields=['job', 'index'], name='jobs_chunk_job_id_e94136_idx'),
        ),
        migrations.AddConstraint(
            model_name='chunk',
            constraint=models.UniqueConstraint(fields=('job', 'index'), name='unique_chunk_per_job'),
        ),
    ]
