# Generated by Django 6.0.1 on 2026-02-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_chunk_unique_together_alter_chunk_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='output_file',
            field=models.FileField(blank=True, null=True, upload_to='media/audio/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='chunk',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='chunks/%Y/%m/%d'),
        ),
    ]
